# Use an official Node.js image as the base image
FROM node:14

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY /root/backend devops-fullstack-app/frontend/package*.json 

# Install Node.js dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY devops-fullstack-app/frontend/ .

# Expose the port your app will run on
EXPOSE 3000

# Command to run your application
CMD ["npm", "start"]
