# Use an official Node.js image as the base image
FROM node:14


# Set the working directory inside the container
WORKDIR  https://github.com/shubhamkalsait/devops-fullstack-app.git

# Copy package.json and package-lock.json to the working directory
ADD https://github.com/shubhamkalsait/devops-fullstack-app.git /root/backend

# Install Node.js dependencies
RUN npm install


# Expose the port your app will run on
EXPOSE 3000

# Command to run your application
CMD ["npm", "start"]
