##Install nodejs for docker
FROM centos:7
ADD curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh
ADD curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
COPY .bashrc /root/.bashrc
CMD ["bash", "root", "/root/.bashrc"]
RUN nvm install v14.10.0
RUN apt install git 
RUN mkdir cdec-b19
WORKDIR  cdec-b19/
RUN git init
ADD git pull https://github.com/shubhamkalsait/devops-fullstack-app.git
WORKDIR /frontend
RUN npm install
EXPOSE 3000
CMD nvm -DFOREGROUND